### PR TITLE
Froggymark + Batcher optimizations

### PR DESCRIPTION
**Pull request by MrBrixican**
- [Reorganized vs solution to have a sample folder](https://github.com/NoelFB/Foster/commit/4d7cb69320415d37c159d160f214bf12d84e214e)
- [Renamed Batch.cs to Batcher.cs to be consistent with class name](https://github.com/NoelFB/Foster/commit/0068956a0bd38225a40981a8a70b1cadd8cd1f0a)
- [Changed vertex init from pointer/constructor to span/accessor](https://github.com/NoelFB/Foster/commit/5ccce6e3db8c862ab7c27ad317c0c03304835ee9)
  - I was surprised that the original pointer based rework didn't improve performance, but actually harmed it. So I did some digging and it seems that for some bizarre reason the Vertex struct constructor was really hurting performance (~30% penalty). 
  - Thus, I changed all of the vertex init code to use accessors instead.
  - Also changed most vertex/index operations to use Spans as they're slightly more performant with constant indexes compared to pointer increments.
  - Slightly controversial, I made it so untextured shapes do not set the vertex texture coordinates. The shader ignores it anyways so I figured it was wasted ops. Feel free to request me to zero them out if that bothers you.
  - All of these changes have been tested via micro benchmarks using BenchmarkDotNet, hence why I left FlipVerticalUVs alone since it performs better than any span implementation I could come up with, haha.
- [Bunnymark](https://github.com/NoelFB/Foster/commit/0303a4c06429e57e38e3889a2c507f56ca6a6d24)
  - I really like that Foster gives you a high level API through Batcher and low level through Mesh/DrawCommand, so I thought it would be neat to show that off using a pretty well known (for better or worse, haha) demo.
  - Batcher actually does a really solid job, so the only way I could beat it was by doing less (smaller vertex, one time index buffer allocation, etc).
  - It includes a brief readme with my personal stats (pretty good for a small laptop), asset license information, and a disclaimer because some people obsess over weird benchmarks like this.

### CODE REVIEW

**Comment by NoelFB** [comment]
Hey, this all sounds pretty good to me ... A few things:

- I'm also surprised the Vertex constructor is slower, but it definitely does seem to be for me too. I even tried adding a `[SkipLocalsInit]` attribute and `AggressiveInlining` to the constructors, along with making a constructor that doesn't take texture uv's and it still seems slower. Weird!
- I'm happy to include your test example, although I wonder if we should change the image? It's probably fine. The only other thing that needs fixing is to use `Path.Join` in your asset loading, instead of a backslack `\` as the assets fail to load on Linux/Mac right now.
- I wonder if instead of renaming Batch -> Batcher, we rename the file to `Batch.cs`? I suppose Batch might not be a clear enough name, in which case I wonder if it should just be called SpriteBatch like XNA's implementation.... will think about this a bit but happy for input.

Also thanks for the pull request! I appreciate the input here :)

**Comment by MrBrixican** [comment]
Good catch on the `Path.Join`.

I actually took this image from a Raylib [example](https://github.com/raysan5/raylib/blob/master/examples/textures/resources/wabbit_alpha.png). I don't think they're sure where it comes from either, but I've seen variations of this image used across many bunnymark demos. As you said, probably fine, but I'm open to change if needed.

As for the name for Batcher/Batch, I'd say Batcher is more consistent with another similar class, Packer. However, XNA-likes and libGDX usually follow a __Batch naming scheme. Finally, Batch is probably more likely to conflict with other (sub)class names in future. I don't have a particularly strong attachment to either, so I'll let you decide.

Also, I'm wondering if we could enable GitHub discussions for this repo? Some other place than PRs to discuss ideas/features, haha.

**Comment by NoelFB** [comment]
Yeah that makes sense, I agree with the Batch -> Batcher rename; it fits Packer. Down the road we can consider potentially renaming both to SpriteBatcher/SpritePacker but I think they're fine like that.

Also while I'm fine with the bunny sprite I'm gonna suggest using this one since it's mine and I'm fine with it being MIT and then we're just sure of the origin :)

frog

Otherwise I think I'm good to merge this! I also enabled Discussions. I might also enable Wiki in the future but will leave it off for now.

**Comment by MrBrixican** [comment]
Frogs have been added. So many frogs...

**Comment by NoelFB** [comment]
lol, awesome. Will merge, thanks for the work here! :)

**Pull request merged**
