### PR TITLE
Improvements

### LINKED ISSUE #34: Graphics.Clear depth should be double, not int
`Graphics.Clear(Color color, int depth, int stencil, ClearMask mask)` should be using a `double` for `depth`.

### PR DESCRIPTION
**Pull request by amerkoleci**
- Update SDL to latest stable 2.28.5
- Modernize CMake usage
- Use float for clear depth, fixes #34

### CODE REVIEW

**Comment by MrBrixican** [comment]
We should probably be using `double` as `glClearDepth` uses `double` not `float`, and our depth buffers have 24 bits of precision, more than the 16 max we could specify via `float`.

**Comment by amerkoleci** [comment]
> We should probably be using `double` as `glClearDepth` uses `double` not `float`, and our depth buffers have 24 bits of precision, more than the 16 max we could specify via `float`.

Mmm, d3d11 for example uses float

**Comment by MrBrixican** [comment]
You know what, I screwed up on the math. floats have 32 bits, not 16. Ignore what I said, floats are fine.

**Comment by amerkoleci** [comment]
> You know what, I screwed up on the math. floats have 32 bits, not 16. Ignore what I said, floats are fine.

Saw that, don't worry :)

**Comment by NoelFB** [comment]
Looks good, thanks! :D

**Pull request merged**
